debian/tmp/usr/bin
debian/tmp/usr/sbin
debian/tmp/usr/lib/lib*.so.*
debian/tmp/usr/share/xml/shibboleth
debian/tmp/etc/shibboleth
debian/tmp/usr/lib/shibboleth
debian/tmp/var/run/shibboleth

debian/shib.load	etc/apache2/mods-available
debian/shib.conf	etc/apache2/mods-available

debian/tmp/usr/share/doc/shibboleth/logo.jpg	usr/share/shibboleth
debian/tmp/usr/share/doc/shibboleth/main.css	usr/share/shibboleth

debian/tmp/usr/share/doc/shibboleth/*.txt	usr/share/doc/libapache2-mod-shib2
